config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  auth = Rails.application.credentials.dig(Rails.env.to_sym, :admin_auth)
  if auth.present?
    GoodJob::Engine.middleware.use(Rack::Auth::Basic) do |username, password|
      ActiveSupport::SecurityUtils.secure_compare(username, auth[:username]) &
        ActiveSupport::SecurityUtils.secure_compare(password, auth[:password])
    end
  end

  mount GoodJob::Engine, at: 'good_job'
  mount Blazer::Engine, at: 'blazer'
  mount PgHero::Engine, at: 'pghero'

  get '/about' => 'pages#about', as: :about
  get '/imprint' => 'pages#imprint', as: :imprint
  get '/privacy' => 'pages#privacy', as: :privacy
  get '/transparency' => 'pages#transparency', as: :transparency
  get '/mcp' => 'pages#mcp', as: :mcp

  get '/not_found' => 'errors#not_found', as: :foo
  get '/404' => 'errors#not_found', as: :not_found
  get '/500' => 'errors#exception', as: :exception

  post '/api/mcp' => 'mcp/server#index', as: :mcp_server

  root to: 'pages#home'

  scope '(:district)' do
    get :search, to: 'search#show'

    resources :documents, only: %i[index show] do
      collection do
        get :suggest

        get :allris
      end
    end

    resources :meetings, only: %i[index show] do
      collection do
        get :allris
      end

      member do
        get :minutes, path: 'protokoll'
      end
    end

    resources :agenda_items, only: [] do
      collection do
        get :allris
        get :suggest
      end
    end

    resources :committees, only: %i[index show]

    resource :calendar, only: :show

    resource :map, only: :show do
      collection do
        get :markers
      end
    end

    resources :locations, only: :show

    resource :statistics, only: :show

    resource :admin, only: :show, controller: :admin

    root to: 'districts#show', as: :root_with_district
  end
end

app/controllers/search_controller.rb
# frozen_string_literal: true

class SearchController < ApplicationController
  LIMIT = 25

  def show
    @term = (params[:q] || '').strip

    if @district.present? && (document = @district.documents.find_by(number: @term))
      redirect_to document_path(document) and return
    end

    @kinds = (@district.present? ? @district.documents.distinct.order(:kind).pluck(:kind) : [])

    set_search_options

    search_documents
    search_agenda_items
  end

  def search_documents
    documents_root = (@all_districts ? Document.all : @district.documents).complete.include_meetings

    documents_root = documents_root.where(kind: @kind) if @kind
    documents_root = documents_root.joins(:attachments) if @attachments

    @documents = Document.search(@term, root: documents_root, order: @order, attachments: @attachments)
    @more_documents = [@documents.count(:all) - LIMIT, 0].max
    @documents = @documents.limit(LIMIT)
  end

  def search_agenda_items
    agenda_items_root = (@all_districts ? AgendaItem.all : @district.agenda_items).includes(:meeting)

    @agenda_items = AgendaItem.minutes_prefix_search(@term, agenda_items_root)
    @more_agenda_items = [@agenda_items.count - LIMIT, 0].max
    @agenda_items = @agenda_items.limit(LIMIT)
  end

  protected

  def set_search_options
    @order = :relevance if params[:order] == 'relevance'
    @order ||= :date

    @attachments = params[:attachments] == 'true'
    @all_districts = params[:all_districts] == 'true' || @district.blank?

    @kind = params[:kind] if params[:kind].present? && @kinds.include?(params[:kind])
  end
end

app/views/search/show.html.slim
h1.mb-4
  ' Suchergebnisse für '#{@term}'

= form_tag search_path, method: :get do
  = hidden_field_tag :q, @term
  .row
    .col-12.col-lg
      .form-group
        = select_tag :kind, options_for_select(@kinds, @kind), include_blank: 'Alle Drucksachenarten', class: 'form-control'
    .col-6.col-lg
      .form-group.form-check.mt-1
        => check_box_tag :attachments, 'true', @attachments
        label for="attachments"
          | Auch Anhänge
    .col-6.col-lg
      .form-group.form-check.mt-1
        => check_box_tag :all_districts, 'true', @all_districts
        label for="all_districts"
          | Alle Bezirke
    .col-6.col-lg
      => select_tag :order, options_for_select([['Nach Relevanz', :relevance], ['Nach Datum', :date]], @order), class: 'form-control'
    .col-12.col-lg.text-end
      button.btn.btn-primary.text-nowrap type="submit"
        | Suche aktualisieren

.row.mt-4.border-bottom.font-weight-bold
  .col-2.col-lg-1.py-2 Drs. / TOP
  .col.col-lg-7.py-2 Titel / Art
  .col-10.col-lg.offset-2.offset-lg-0.py-2 Befassung
  .col-1

- @documents.uniq.each do |document|
  .row.pt-3.border-top
    .col-2.col-lg-1.text-nowrap
      = link_to document_path(document, district: document.district), title: document.ranking do
        strong= highlight(document.number, @term)
    .col.col-lg-7
      = link_to document_path(document, district: document.district) do
        = highlight(strip_tags(document.title), @term)
      br
      span.text-secondary= document.kind
    .col-1.order-lg-last.text-end
      = allris_link(document.allris_url)
    .w-100.d-block.d-lg-none
    .col.offset-2.offset-lg-0.pt-2.pt-lg-0
        td
          - if (meeting = document.meetings.first)
            = link_to meeting.committee.name, meeting_path(meeting, district: meeting.district), class: 'text-secondary'
            br
            = l meeting.date
          - if @all_districts
            strong=< document.district.name

  .row.mt-2
    .col.offset-2.offset-lg-1
      p
        = highlight_multi_excerpt(document.full_text, @term)
      - if @attachments
        p.excerpt.mt-2
          = highlight_multi_excerpt(document.attachments_content, @term)

- @agenda_items.each do |agenda_item|
  - meeting = agenda_item.meeting

  .row.pt-3.border-top
    .col-2.col-lg-1.text-nowrap
      = link_to minutes_meeting_path(meeting, anchor: agenda_item.id) do
        strong= agenda_item.number
    .col.col-lg-7
      = link_to minutes_meeting_path(meeting, anchor: agenda_item.id) do
        = highlight(strip_tags(agenda_item.title), @term)
      br
      span.text-secondary Protokoll
    .col-1.order-lg-last.text-end
      = allris_link(agenda_item.meeting.allris_url)
    .w-100.d-block.d-lg-none
    .col.offset-2.offset-lg-0.pt-2.pt-lg-0
        td
          = link_to meeting.committee.name, meeting_path(meeting, district: meeting.district), class: 'text-secondary'
          br
          = l meeting.date
          - if @all_districts
            strong=< meeting.district.name

  .row.mt-2
    .col.offset-2.offset-lg-1
      p
        = highlight_multi_excerpt(strip_tags(agenda_item.minutes), @term)

- if @more_documents.positive? || @more_agenda_items.positive?
  p.mt-4
    strong
      | Sowie weitere #{@more_documents} / #{@more_agenda_items} Ergebnisse in Drucksachen / Protokollen.
        Schränken Sie die Suche weiter ein, um alle Ergebnisse zu sehen.