config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  auth = Rails.application.credentials.dig(Rails.env.to_sym, :admin_auth)
  if auth.present?
    GoodJob::Engine.middleware.use(Rack::Auth::Basic) do |username, password|
      ActiveSupport::SecurityUtils.secure_compare(username, auth[:username]) &
        ActiveSupport::SecurityUtils.secure_compare(password, auth[:password])
    end
  end

  mount GoodJob::Engine, at: 'good_job'
  mount Blazer::Engine, at: 'blazer'
  mount PgHero::Engine, at: 'pghero'

  get '/about' => 'pages#about', as: :about
  get '/imprint' => 'pages#imprint', as: :imprint
  get '/privacy' => 'pages#privacy', as: :privacy
  get '/transparency' => 'pages#transparency', as: :transparency
  get '/mcp' => 'pages#mcp', as: :mcp

  get '/not_found' => 'errors#not_found', as: :foo
  get '/404' => 'errors#not_found', as: :not_found
  get '/500' => 'errors#exception', as: :exception

  post '/api/mcp' => 'mcp/server#index', as: :mcp_server

  root to: 'pages#home'

  scope '(:district)' do
    get :search, to: 'search#show'

    resources :documents, only: %i[index show] do
      collection do
        get :suggest

        get :allris
      end
    end

    resources :meetings, only: %i[index show] do
      collection do
        get :allris
      end

      member do
        get :minutes, path: 'protokoll'
      end
    end

    resources :agenda_items, only: [] do
      collection do
        get :allris
        get :suggest
      end
    end

    resources :committees, only: %i[index show]

    resource :calendar, only: :show

    resource :map, only: :show do
      collection do
        get :markers
      end
    end

    resources :locations, only: :show

    resource :statistics, only: :show

    resource :admin, only: :show, controller: :admin

    root to: 'districts#show', as: :root_with_district
  end
end

app/controllers/api/v1/documents_controller.rb
# frozen_string_literal: true

class Api::V1::DocumentsController < Api::V1::BaseController
  SEARCH_LIMIT = 25

  def show
    @document = Document.complete.find(params[:id])
    render json: document_json(@document)
  end

  def search
    term = (params[:q] || '').strip

    return render_error('Search term cannot be empty') if term.blank?

    documents_query = build_documents_query(term)
    documents = documents_query.limit(SEARCH_LIMIT)

    render json: {
      documents: documents.map { |doc| document_json(doc) },
    }
  end

  private

  def document_json(document)
    {
      id: document.id,
      number: document.number,
      title: document.title,
      kind: document.kind,
      author: document.author,
      content: document.content,
      resolution: document.resolution,
      attached: document.attached,
      created_at: document.created_at,
      updated_at: document.updated_at,
      url: document_url(document, district: document.district),
      district: {
        id: document.district.id,
        name: document.district.name,
      },
      meetings: document.meetings.map do |meeting|
        {
          id: meeting.id,
          title: meeting.title,
          date: meeting.date,
          start_time: meeting.start_time,
          end_time: meeting.end_time,
        }
      end,
    }
  end

  def build_documents_query(term)
    order = params[:order] == 'relevance' ? :relevance : :date
    attachments = params[:attachments] == 'true'
    kind = params[:kind].presence

    district = District.lookup!(params[:district]) if params[:district].present?

    documents_root = district.present? ? district.documents : Document.all
    documents_root = documents_root.complete.include_meetings
    documents_root = documents_root.where(kind: kind) if kind
    documents_root = documents_root.joins(:attachments) if attachments

    Document.search(term, root: documents_root, order: order, attachments: attachments)
  end
end

app/controllers/documents_controller.rb
# frozen_string_literal: true

class DocumentsController < ApplicationController
  include ActionView::Helpers::TextHelper

  skip_after_action :track_event, only: :suggest

  MAX_SUGGESTIONS = 5

  def index
    @documents = @district.documents.complete.include_meetings.latest_first.page(params[:page])
    @title = "Drucksachen der Bezirksversammlung #{@district.name} und ihrer Gremien"
  end

  def show
    @document = Document.complete.find(params[:id]&.split('-')&.last)
    full_document_path = document_path(@document, district: @document.district)
    redirect_to(full_document_path, status: :moved_permanently) and return unless request.path == full_document_path

    @title = "#{@document.number} - #{helpers.strip_tags(@document.title)&.squish&.truncate(50)} - #{@district.name}"
    @meta_description = helpers.strip_tags(@document.content)&.squish&.truncate(150)
    @noindex = @document.noindex
  end

  def allris
    redirect_to root_path and return if @district.blank?

    @document = @district.documents.find_by!(allris_id: params[:allris_id])
    redirect_to(document_path(@document, district: @document.district))
  end

  def suggest
    root = @district&.documents || Document.all
    documents = Document.prefix_search(params[:q], root.includes(:district)).limit(MAX_SUGGESTIONS).load
    documents = documents.map do |document|
      {
        id: document.id,
        path: document_path(document),
        title: document.title,
        number: document.number,
        district: document.district.name,
        kind: document.kind,
        excerpt: excerpt(strip_tags(document.full_text), params[:q], radius: 50),
      }
    end
    render json: documents
  end
end

app/helpers/documents_helper.rb
# frozen_string_literal: true

module DocumentsHelper
  DOCUMENT_NUMBER_PATTERN = /(\d{2}-\d{4}(\.\d{1,2})+)/
  IMAGE_LINK_PATTERN = /img src="([^"]*)"/

  def link_documents(content, district)
    numbers = content.scan(DOCUMENT_NUMBER_PATTERN).flatten
    documents = district.documents.where(number: numbers).index_by(&:number)

    content.gsub DOCUMENT_NUMBER_PATTERN do |number|
      document = documents[number]
      if document
        link_to number, document_path(document), title: strip_tags(document.title), data: { toggle: :tooltip, placement: :bottom }
      else
        number
      end
    end
  end

  def link_images(content, document)
    content.gsub(IMAGE_LINK_PATTERN) do |_src|
      src = Regexp.last_match(1)&.squish
      image = document.images.attachments.find { |a| a.filename == File.basename(src) }
      if image.present?
        "img src=\"#{rails_blob_path(image)}\" class=\"img-fluid\""
      else
        'span'
      end
    end
  end

  def document_format(document, attribute)
    content = document.send(attribute.to_sym)

    return '' if content.nil?

    content = scrub_whitespace(content)
    content = link_documents(content, document.district)
    content = link_images(content, document)

    Rinku.auto_link(content, :all, 'target="_blank"')
  end

  def scrub_whitespace(content)
    content = content.gsub(%r{<span[^>]*>[  ]*</span>}, ' ')
    content.gsub(%r{<p[^>]*>[  ]*</p>}, ' ')
  end

  def highlight_multi_excerpt(text, terms)
    multiple_terms = terms.squish.split
    multi_excerpt = multiple_terms.map do |term|
      excerpt(text, term, radius: 100)
    end.join(' ')

    highlight(multi_excerpt, multiple_terms)
  end

  def structured_data_for_document(document)
    {
      '@context': 'http://schema.org',
      '@type': 'Article',
      mainEntityOfPage: {
        '@type': 'WebPage',
        '@id': document_url(document),
      },
      headline: document.title.squish,
      image: [],
      articleBody: document.full_text&.squish || '',
      articleSection: document.district.name,
      datePublished: document.created_at.iso8601,
      dateModified: document.updated_at.iso8601,
      publisher: {
        '@type': 'Organization',
        name: "Bezirksversammlung #{document.district.name}",
      },
      isAccessibleForFree: 'True',
      description: strip_tags(document.content)&.squish&.truncate(200) || '',
    }
  end
end

app/views/documents/index.html.slim
h1.h2
  ' Alle Drucksachen

  small.text-muted= number_with_delimiter @documents.total_count

.row.mt-4.border-bottom.font-weight-bold
  .col-2.col-lg-1.py-2 Drs.
  .col.col-lg-7.py-2 Titel / Art
  .col-10.col-lg.offset-2.offset-lg-0.py-2 Letzte Befassung
  .col-1

- @documents.each do |document|
  .row.pt-3.border-top
    .col-2.col-lg-1.text-nowrap
      = link_to document_path(document) do
        strong= document.number
    .col.col-lg-7
      = link_to document_path(document) do
        = document.title.html_safe
      br
      span.text-secondary= document.kind
    .col-1.order-lg-last.text-end
      = allris_link(document.allris_url)
    .w-100.d-block.d-lg-none
    .col.offset-2.offset-lg-0.pt-2.pt-lg-0
      - if (meeting = document.meetings.latest_first.first)
        = link_to meeting.committee.name, meeting_path(meeting), class: 'text-secondary'
        br
        = l meeting.date

.mt-5
  = paginate @documents, theme: 'bootstrap-5', nav_class: "nav justify-content-center"

app/views/documents/search.html.slim
h1.mb-4
  ' Suchergebnisse für '#{@term}'

= form_tag search_documents_path, method: :get do
  = hidden_field_tag :q, @term
  .row
    .col-12.col-lg
      .form-group
        = select_tag :kind, options_for_select(@kinds, @kind), include_blank: 'Alle Drucksachenarten', class: 'form-control'
    .col-6.col-lg
      .form-group.form-check.mt-1
        => check_box_tag :attachments, 'true', @attachments
        label for="attachments"
          | Auch Anhänge
    .col-6.col-lg
      .form-group.form-check.mt-1
        => check_box_tag :all_districts, 'true', @all_districts
        label for="all_districts"
          | Alle Bezirke
    .col-6.col-lg
      => select_tag :order, options_for_select([['Nach Relevanz', :relevance], ['Nach Datum', :date]], @order), class: 'form-control'
    .col-12.col-lg.text-end
      button.btn.btn-primary.text-nowrap type="submit"
        | Suche aktualisieren

.row.mt-4.border-bottom.font-weight-bold
  .col-2.col-lg-1.py-2 Drs.
  .col.col-lg-7.py-2 Titel / Art
  .col-10.col-lg.offset-2.offset-lg-0.py-2 Befassung
  .col-1

- @documents.uniq.each do |document|
  .row.pt-3.border-top
    .col-2.col-lg-1.text-nowrap
      = link_to document_path(document, district: document.district), title: document.ranking do
        strong= highlight(document.number, @term)
    .col.col-lg-7
      = link_to document_path(document, district: document.district) do
        = highlight(strip_tags(document.title), @term)
      br
      span.text-secondary= document.kind
    .col-1.order-lg-last.text-end
      = allris_link(document.allris_url)
    .w-100.d-block.d-lg-none
    .col.offset-2.offset-lg-0.pt-2.pt-lg-0
        td
          - if (meeting = document.meetings.first)
            = link_to meeting.committee.name, meeting_path(meeting, district: meeting.district), class: 'text-secondary'
            br
            = l meeting.date

  .row.mt-2
    .col.offset-2.offset-lg-1
      p
        = highlight_multi_excerpt(document.full_text, @term)
      - if @attachments
        p.excerpt.mt-2
          = highlight_multi_excerpt(document.attachments_content, @term)

.mt-5
  = paginate @documents, theme: 'bootstrap-5', nav_class: "nav justify-content-center"

app/views/documents/show.html.slim
h2.h1 title="Drucksache #{@document.number}"
  strong= @document.number
  .float-end= allris_link(@document.allris_url)
h1.h2.text-break
  = simple_format(@document.title)
h3.text-muted
  small= @document.kind

- attachments = @document.attached.present? || @document.attachments.present?
- agenda_items = @document.agenda_items.by_meeting
- related_documents = @document.related_documents.order(:number)

- if item = agenda_items.first
  p
    ' Letzte Beratung:
    => l item.meeting.date
    => link_to item.meeting.committee.name, meeting_path(item.meeting)
    - if item.allris_id.present?
      => link_to minutes_meeting_path(item.meeting, anchor: item.id), title: "Protokoll zu #{item.number}", data: { bs_toggle: :tooltip } do
        strong= item.number
      = meeting_result_badge(item)
    - else
      = item.number

.row
  .col-md-8
    .card.mt-3
      .card-header.fw-bold Sachverhalt
      .card-body
        == document_format(@document, :content)

    - if @document.resolution.present?
      .card.mt-3
        .card-header.fw-bold Petitum/Beschluss
        .card-body
          == document_format(@document, :resolution)

  .col-md-4
    - if agenda_items.present?
      .card.mt-3
        .card-header.fw-bold
          | Bera&shy;tungs&shy;reihen&shy;folge
        .card-body
          .row
            .col-9.border-bottom.py-2 Datum/Gremium
            .col-3.border-bottom.py-2.text-end TOP

          - agenda_items.each do |item|
            .row.py-2.border-top
              .col-9.fw-bold
                = l item.meeting.date
              .col-3.text-end
                - if item.allris_id.present?
                  => link_to minutes_meeting_path(item.meeting, anchor: item.id), title: "Protokoll zu #{item.number}", data: { bs_toggle: :tooltip } do
                    strong= item.number
                  = meeting_result_badge(item)
                - else
                  = item.number
              .col.col-12
                = link_to item.meeting.committee.name, meeting_path(item.meeting)

    - if attachments
      .card.mt-3
        .card-header.fw-bold Anhänge
        .card-body
          == document_format(@document, :attached)

          .mt-3
            - @document.attachments.by_name.each do |attachment|
              = link_to attachment.name, rails_blob_path(attachment.file, disposition: :inline), target: '_blank'
              br

    - if related_documents.present?
      .card.mt-3
        .card-header.fw-bold Verwandte Drucksachen
        .card-body
          - related_documents.each do |related_document|
            .mt-3
              = link_to document_path(related_document) do
                strong>= related_document.number
                = related_document.title.html_safe

    .card.mt-3
      .card-header.fw-bold
        ' Lokalisation
        span.badge.text-bg-warning.float-end Beta

      .card-body
        - if @document.locations.present?
          - @document.locations.each do |location|
            => link_to location_path(location) do
              span.badge.text-bg-secondary data-bs-toggle='tooltip' data-bs-title=location.formatted_address
                = location.name
        - else
          p
            | Keine Orte erkannt.

        p.small.text-secondary.mt-3
          | Die Erkennung von Orten anhand des Textes der Drucksache kann ungenau sein. Es ist daher möglich, das Orte
            gar nicht oder falsch erkannt werden.



script type="application/ld+json"
  == structured_data_for_document(@document).to_json