config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  auth = Rails.application.credentials.dig(Rails.env.to_sym, :admin_auth)
  if auth.present?
    GoodJob::Engine.middleware.use(Rack::Auth::Basic) do |username, password|
      ActiveSupport::SecurityUtils.secure_compare(username, auth[:username]) &
        ActiveSupport::SecurityUtils.secure_compare(password, auth[:password])
    end
  end

  mount GoodJob::Engine, at: 'good_job'
  mount Blazer::Engine, at: 'blazer'
  mount PgHero::Engine, at: 'pghero'

  get '/about' => 'pages#about', as: :about
  get '/imprint' => 'pages#imprint', as: :imprint
  get '/privacy' => 'pages#privacy', as: :privacy
  get '/transparency' => 'pages#transparency', as: :transparency
  get '/mcp' => 'pages#mcp', as: :mcp

  get '/not_found' => 'errors#not_found', as: :foo
  get '/404' => 'errors#not_found', as: :not_found
  get '/500' => 'errors#exception', as: :exception

  post '/api/mcp' => 'mcp/server#index', as: :mcp_server

  root to: 'pages#home'

  scope '(:district)' do
    get :search, to: 'search#show'

    resources :documents, only: %i[index show] do
      collection do
        get :suggest

        get :allris
      end
    end

    resources :meetings, only: %i[index show] do
      collection do
        get :allris
      end

      member do
        get :minutes, path: 'protokoll'
      end
    end

    resources :agenda_items, only: [] do
      collection do
        get :allris
        get :suggest
      end
    end

    resources :committees, only: %i[index show]

    resource :calendar, only: :show

    resource :map, only: :show do
      collection do
        get :markers
      end
    end

    resources :locations, only: :show

    resource :statistics, only: :show

    resource :admin, only: :show, controller: :admin

    root to: 'districts#show', as: :root_with_district
  end
end

app/models/committee.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: committees
#
#  id               :bigint           not null, primary key
#  average_duration :integer
#  inactive         :boolean          default(FALSE)
#  name             :string
#  order            :integer          default(0)
#  public           :boolean          default(TRUE)
#  created_at       :datetime         not null
#  updated_at       :datetime         not null
#  allris_id        :integer
#  district_id      :bigint
#
# Indexes
#
#  index_committees_on_allris_id    (allris_id)
#  index_committees_on_district_id  (district_id)
#
class Committee < ApplicationRecord
  LOCAL_COMMITTEE_DESIGNATION = 'Regionalausschuss'

  belongs_to :district
  has_many :meetings, dependent: :nullify
  has_many :committee_members, dependent: :destroy
  has_many :members, through: :committee_members

  scope :open, -> { where(public: true) }
  scope :active, -> { where(inactive: false) }
  scope :by_order, -> { order(:order) }

  def update_average_duration!
    total_duration = 0
    meetings.with_duration.find_each do |meeting|
      total_duration += meeting.duration
    end

    self.average_duration = (total_duration.to_f / meetings.with_duration.count).round

    save!
  end

  def local?
    name.include?(LOCAL_COMMITTEE_DESIGNATION)
  end

  def area
    return nil unless local?

    name.gsub(LOCAL_COMMITTEE_DESIGNATION, '')&.strip
  end

  def matches_area?(location_name)
    return false unless local?
    return false if location_name.blank?

    normalized_location_name = location_name.gsub(/[^\w ]/, '').downcase
    area&.gsub(/[^\w ]/, '')&.downcase == normalized_location_name
  end
end

app/controllers/committees_controller.rb
# frozen_string_literal: true

class CommitteesController < ApplicationController
  def index
    @committees = @district.committees.open.order(:inactive, :order)
    @title = "Gremien und Ausschüsse der Bezirksversammlung #{@district.name}"
  end

  def show
    @committee = @district.committees.find(params[:id])
    @documents_timeline = @district.documents.committee(@committee).in_last_months(12).group_by_month('meetings.date').count
    @title = "#{@committee.name} - #{@committee.district.name}"
  end
end

app/views/committees/index.html.slim
h1.h2
  ' Gremien / Ausschüsse

.table-responsive
  table.table.mt-4
    thead
      th Name
      th Nächste Sitzung
      th Durchschnittliche Dauer
      th

    tbody
      - @committees.each do |committee|
        - meeting = committee.meetings.in_future.order(:date).first
        tr
          td
            => link_to committee_path(committee) do
              strong= committee.name
            - if committee.inactive?
              span.badge.text-bg-secondary Inaktiv
          td.text-nowrap
            - if meeting
              = link_to meeting_path(meeting) do
                = l meeting.date
              br
              = l meeting.start_time
            - else
              | -
          td
            - if committee.average_duration
              = "#{number_with_precision(committee.average_duration.to_f / 3600, precision: 2)} h"
            - else
              | -
          td
            - if meeting
              = allris_link meeting.allris_url

app/views/committees/show.html.slim
h2.h1
  strong>= @committee.name
- if @committee.inactive?
  h3
    span.badge.badge-secondary Ausschuss ist inaktiv

- unless @committee.inactive?
  h5.text-muted Anzahl Drucksachen im Verlauf der letzten 12 Monate
  = column_chart @documents_timeline, height: '100px'

.table-responsive
  table.table.mt-4
    thead
      th Datum
      th Titel
      th.text-end TOPs
      th

    tbody
      - @committee.meetings.with_agenda.latest_first.each do |meeting|
        tr class="#{meeting.date == Time.zone.now.to_date ? 'table-warning' : nil}"
          td.text-nowrap
            = link_to meeting_path(meeting) do
              strong= l meeting.date
            - if meeting.start_time.present?
              br
              = l meeting.start_time
          td
            = link_to meeting_path(meeting) do
              = meeting.title.html_safe
          td.text-end
            = meeting.agenda_items.count
          td.text-end.text-nowrap
            - if meeting.logged?
              => meeting_minutes_link(meeting)
            = allris_link meeting.allris_url